### ISSUE TITLE
Error mci_ipm_to_csv _csv.Error: need to escape, but no escapechar set

### ISSUE THREAD

**Issue by MadroxBarros** [adelosa/cardutil#1]
Hi!

Could the error below be caused by missing parameters in the extract call?
The csv file was created but the process return error.

Error:
```
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\mci_ipm_to_csv.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\cardutil\cli\mci_ipm_to_csv.py", line 9, in cli_entry
    cli_run(**vars(cli_parser().parse_args()))
  File "C:\Python310\lib\site-packages\cardutil\cli\mci_ipm_to_csv.py", line 21, in cli_run
    mci_ipm_to_csv(in_ipm=in_ipm, out_csv=out_csv, config=config, **kwargs)
  File "C:\Python310\lib\site-packages\cardutil\cli\mci_ipm_to_csv.py", line 49, in mci_ipm_to_csv
    dicts_to_csv(
  File "C:\Python310\lib\site-packages\cardutil\outputter.py", line 23, in dicts_to_csv
    writer.writerow(item)
  File "C:\Python310\lib\csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
_csv.Error: need to escape, but no escapechar set
```

**Comment by adelosa** [comment]
I have not encounter this issue but it looks like it's caused by data in a field requiring escaping. Maybe a text field in the IPM record with some delimiter characters. 
Would help if you could provide details on how to recreate the issue.

**Comment by adelosa** [comment]
The only way I have been able to recreate this issue is by:

* Changing cardutil.outputter to add the quoting=csv.QUOTE_NONE option to the DictWriter 
* Convert IPM file with a comma in a text field.

So created a test.csv

    MTI,DE2,DE3,DE43
    0100,1111222233334444,111111,BIG BOBS\80 KERNDALE ST\DANERLEY\3103  VICAUS

I ran `mci_csv_to_ipm test.csv` to generate an IPM file.
Then edited the output IPM file (test.csv.ipm) to insert a comma between BIG and BOBS -- so `BIG,BOBS`

I then ran `mci_ipm_to_csv test.csv.ipm` to test the conversion.

```
MTI,DE2,DE3,DE4,DE12,DE14,DE22,DE23,DE24,DE25,DE26,DE30,DE31,DE33,DE37,DE38,DE40,DE41,DE42,DE48,DE49,DE50,DE63,DE71,DE73,DE93,DE94,DE95,DE100,PDS0023,PDS0052,PDS0122,PDS0148,PDS0158,PDS0165,DE43_NAME,DE43_SUBURB,DE43_POSTCODE,ICC_DATA
0100,1111222233334444,111111,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,"BIG,BOBS",DANERLEY,3103,
```

You will note that "BIG,BOBS" has been quoted.. but no error.
To recreate the issue, I had to change the cardutil.outputter module to add the following option to the DictWriter:

```python
    writer = csv.DictWriter(
        output_file,
        quoting=csv.QUOTE_NONE,    # This line was added
        fieldnames=field_list,
        extrasaction="ignore",
        lineterminator="\n")
```

I then run `mci_ipm_to_csv test.csv.ipm` to test the conversion - now I get the error.

```
$ mci_ipm_to_csv test.csv.ipm
Traceback (most recent call last):
  File "/cardutil/venv/bin/mci_ipm_to_csv", line 33, in <module>
    sys.exit(load_entry_point('cardutil', 'console_scripts', 'mci_ipm_to_csv')())
  File "/cardutil/cardutil/cli/mci_ipm_to_csv.py", line 9, in cli_entry
    cli_run(**vars(cli_parser().parse_args()))
  File "/cardutil/cardutil/cli/mci_ipm_to_csv.py", line 21, in cli_run
    mci_ipm_to_csv(in_ipm=in_ipm, out_csv=out_csv, config=config, **kwargs)
  File "/cardutil/cardutil/cli/mci_ipm_to_csv.py", line 49, in mci_ipm_to_csv
    dicts_to_csv(
  File "/cardutil/cardutil/outputter.py", line 24, in dicts_to_csv
    writer.writerow(item)
  File "/python3.9/csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
_csv.Error: need to escape, but no escapechar set
```

I can see you are using Windows, so that may have something to do with it, but I have not observed any differences between the platforms previously..

* Have you changed any code in the cardutil module?
* What version of cardutil are you using (0.5.0)?
* What specific data was being processed to cause this issue if you have not changed the code.

Hopefully with the above, you can recreate the issues and let me know what you find.

**Comment by adelosa** [comment]
Closing the issue as no response - please reopen if you are able to provide more details.

**Comment by MadroxBarros** [comment]
OK, I'll open again, it was the weekend and I'm starting to work now.
Answering your questions:
1 - I didn't make any changes to the carduitl code.
2 - I tried version 0.5.0 and 0.4.2.
3 - Nothing special, I just did the installation by pip and made a call passing the parameters.

**Comment by adelosa** [comment]
Apologies @MadroxBarros -- I forgot it was the weekend. I will have another look and see what I find.

**Comment by adelosa** [comment]
The best I can tell is this issue was caused by using the wrong input encoding parameter. Once the correct value was selected the files were able to be processed.
